config/routes.rb
Km7::Application.routes.draw do
devise_for :users

resources :problems
resources :users
resource :user, only: [:show] do
  collection do
    put 'update_password'
  end
end
namespace :api do
  namespace :v1  do
    resources :tokens,:only => [:create, :destroy]
  end
end

resources :lists do
  member do
    put "add_problem_list:problem_id", action: :add_problem, as: :add_problem
    delete "remove_problem_list/:problem_id", action: :remove_problem, as: :remove_problem
  end
end


  match '/new_user',  to: 'users#new'
  match '/users', to: 'users#index'
  match '/edit_user', to: 'users#edit'
  

  match '/reports', to: 'problems#index'
  match '/report', to: 'problems#new'
  get '/problems/map'
  match '/reports/map', to: 'problems#map'


  match '/lists', to: 'lists#index'
  match '/new_list', to: 'lists#new'

  devise_scope :user do
  root to: "devise/sessions#new"
  end

  match '/help',    to: 'static_pages#help'
  match '/about_us',   to: 'static_pages#about'
  match '/contact_us', to: 'static_pages#contact'
  match '/dashboard', to: 'static_pages#admin_dashboard'

  match "/problems/add_new_comment" => "problems#add_new_comment", :as => "add_new_comment_to_problems", :via => [:post]
  match "/problems/:id/delete_comment" => "problems#delete_comment", :as => "delete_comment_from_problems", :via => [:delete]












end

app/models/list.rb
class List < ActiveRecord::Base
#	acts_as_xlsx :columns => [:id, :name, :description, :active, :user_id, :created_at, :updated_at]
	belongs_to :user
	belongs_to :user
	has_and_belongs_to_many :problems, :uniq => true

	attr_accessible :user_id, :name, :created_at, :description, :active
	validates(:user_id, presence: true)
	validates(:name, presence: true, uniqueness: true)
	validates(:description, presence: true)

	def get_owner_name
		@owner = User.find(self.user_id)
		@owner_name = "No last name"
		if @owner.last_name
			@owner_name = @owner.name + " " + @owner.last_name
		end

		return @owner_name
	end

	def get_owner
		@owner = User.find(self.user_id)
		return @owner_name
	end

	def get_status
		if self.active
			return "Active"
		else
			return "Closed"
		end
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
#require 'zip/zip'

def new
    @list = List.new
    @problems= Problem.all
  end

#Show report details and only show selescted problem in gmap
  def show
    @list = List.find(params[:id])
    @problems = Problem.paginate(page: params[:page])

    #Respond to will create a call to csv and prepare the list for .xls exporting
    #See lists/show.xls.erb for table formatting details
    respond_to do |format|
      format.html # index.html.erb
      format.xlsx{
        render :xlsx => "show", :filename => "#{@list.id}-#{@list.name}-#{@list.created_at.strftime("%b.%d %Y")}.xlsx"
      }
    end
  end


#Show list of reports and show all of them in gmap
  def index
    @lists = List.paginate(page: params[:page])

  end

  def create
    @list = List.new(params[:list])
#Para obtener el usuario actual que esta creando el reporte solo funciona
#por webapp. Su motivo aplicar relación belongs_to de "problems"
    @list.user_id = current_user.id
#Activate the list when it is created, enabling it for use
#If list is closed it will only be browsable, not editable
    @list.active = true

    if @list.save
      flash[:success] = "List saved"
      redirect_to @list
    else
      flash[:error] = 'Incomplete information, list not created'
      redirect_to  lists_path 
    end
  end

  def destroy
# Unassign all contained reports unless already resolved
    @list = List.find(params[:id])
    @list.problems.each do |problem|
      if problem.status!=3
        problem.status = 1
        problem.save
      end
    end
    @list.destroy
    flash[:success] = "List deleted."
    redirect_to lists_url
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
      if @list.update_attributes(params[:list])
        flash[:success] = "List updated"
        redirect_to @list
      else
        flash[:error] = "List update error"
        redirect_to @list
      end
  end

  def add_problem
    @list    = List.find(params[:id])
    @problem = Problem.find(params[:problem_id])

    if !@list.problems.include?(@problem)
      @list.problems << @problem # This appends and saves the problem selected
      #Change the report status, it is now assigned to the owner of the list
      @problem.status = 2
      @problem.assigned_at = Time.now
      @problem.save
      flash[:notice] = "Report added"
      redirect_to @list
    else 
      flash[:notice] = "Report is already on the list"
      redirect_to @list
    end

  end

  def remove_problem
    @list    = List.find(params[:id])
    @problem = Problem.find(params[:problem_id])
    #Change the report status back to being unassigned
    if @problem.status!= 3
      @problem.status = 1
      @problem.save
    end
    @list.problems.destroy(@problem) # This removes the problem selected
    flash[:notice] = "Report removed"


    redirect_to @list 
  end


#  def validates_role(role)
#    raise ActiveRecord::Rollback if self.roles.include? role
#  end

#  def show_problems
#    @list = List.find(params[:id])
#  end

#  def save
#  @list = List.find(params[:id])
#  @problem = Problem.find(params[:problem])
#  if params[:show] == "true"
#    @list.problems << @problem
#  else
#    @list.problems.delete(@problem)
#  end
#  @list.save!
#  render :nothing => true
#  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list.html.erb
<fieldset>
	<div class="control-group">
		<label class="control-label" for="focusedInput">List Name</label>
			<div class="controls">
				<div class="input-xlarge focused" id="focusedInput" type="text">
					<%= f.text_field :name, :placeholder => "Give the list a new name..." %>
				</div>
			</div>
	</div>


	<div class="control-group">
		<label class="control-label" for="focusedInput">Description</label>
			<div class="controls">
				<div class="input-xlarge focused" id="focusedInput" type="text">
					<%= f.text_field :description, :placeholder => "Update list description..." %>
				</div>
			</div>
	</div>

	<div class="form-actions">
		<%= f.submit "Update", class: "btn btn-large btn-success" %>
	</div>

</fieldset>

app/views/lists/edit.html.erb
<% provide(:title, 'Edit List') %>
<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-header" data-original-title>
			<h2><i class="icon-edit"></i><span class="break"></span>Edit List</h2>
		</div>
		<div class="box-content">
	    	<%= form_for @list, :html => {:multipart => true, :class => "form-horizontal" }  do |f| %>
	    	<%= render 'list', f: f %>
			<% end %>
		</div>
	</div><!--/span-->
</div><!--/row-->

app/views/lists/index.html.erb
<% provide(:title, 'Lists') %>

<%= will_paginate %>

<!-- Main content box heading, shape, size, etc -->

<div class="row-fluid fluid-box">		
	<div class="box span12">
		<div class="box-header">
			<h2><i class="icon-list"></i><span class="break"></span></h2>
			<div class="box-icon">
				<%= link_to '#', class: 'btn btn-success btn-setting' do %>
				<i class="icon-plus"></i> New List
				<% end %>
			</div>
		</div>

<!-- Tabbed view of the current user's created lists and if current user is admin 
	the other tab will list all created lists -->
	<div class="box-content">
		<ul class="nav tab-menu nav-tabs tabs-lists" id="myTab">
			<li class="active"><a href="#active">Active Lists</a></li>
			<li><a href="#closed">Closed Lists</a></li>
		</ul>
		<!-- Create partial for list indexing to eleminite repeated code -->
		<div id="myTabContent" class="tab-content">
			<!-- Content for all lists tab -->
			<div class="tab-pane active" id="active">
				<table class="table table-striped table-bordered bootstrap-datatable datatable">
					<thead>
						<tr>
							<th>ID</th>
							<th>Title</th>
							<th>Description</th>
							<th>Status</th>
							<th>Owner</th>
							<th>Date Created</th>
							<th>Reports</th>
							<th>Actions</th>

						</tr>
					</thead>   
					<tbody>
						<% @lists.where(active: true).each do |list| %>
						<tr>
							<td><%= list.id %></td>
							<td><%= list.name %></td>
							<td><%= list.description %></td>
							<td><%= list.get_status %></td>
							<td><%= list.get_owner_name %></td>
							<td><%= list.created_at.strftime(" %b.%d %Y") %></td>
							<td><%= list.problems.size %></td>
							<!--Action buttons for list index table, Delete and More Info -->
							<td class="center">
								<%= link_to list, class: 'btn btn-info' do %>
									<i class="icon-zoom-in icon-white"></i> 
								<% end %>
								<% if current_user.admin? || current_user.id==list.user_id %>
									<%= link_to list, method: :delete, data: { confirm: "Delete this list?" }, class: 'btn btn-danger' do %>
										<i class="icon-trash icon-white"></i> 
									<% end %>
								<% end %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>

			<div class="tab-pane" id="closed">
				<table class="table table-striped table-bordered bootstrap-datatable datatable">
					<thead>
						<tr>
							<th>ID</th>
							<th>Title</th>
							<th>Description</th>
							<th>Status</th>
							<th>Owner</th>
							<th>Date Created</th>
							<th>Reports</th>
							<th>Actions</th>
						</tr>
					</thead>   
					<tbody>
						<% @lists.where(active: false).each do |list| %>
						<tr>
							<td><%= list.id %></td>
							<td><%= list.name %></td>
							<td><%= list.description %></td>
							<td><%= list.get_status %>
							<td><%= list.get_owner_name %></td>
							<td><%= list.created_at.strftime(" %b.%d %Y") %></td>
							<td><%= list.problems.size %></td>
							<!--Action buttons for last column of list index table, Delete and More Info -->
							<td>
								<%= link_to list, class: 'btn btn-info' do %>
								<i class="icon-zoom-in icon-white"></i> 
								<% end %>
								<% if current_user.admin? || current_user.id==list.user_id %>
								<%= link_to list, method: :delete, data: { confirm: "Delete this list?" }, class: 'btn btn-danger' do %>
								<i class="icon-trash icon-white"></i> 
								<% end %>
								<% end %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>



		</div>            
	</div>
</div><!--/span-->
</div><!--/row-->
<%= will_paginate %>

<%= form_for :list, :html => {:class => "form-horizontal"} do |f| %>

	<div class="modal hide fade" id="myModal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"></button>
			<h3>New List Details</h3>
		</div>

		<div class="modal-body">
			<div class="control-group">
				<label class="control-label" for="focusedInput">*List Name</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_field :name,  :maxlength=>'30', :placeholder => "Give the list a new name..." %>
					</div>
				</div>
			</div>


			<div class="control-group">
				<label class="control-label" for="focusedInput">*Description</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_area :description, size: "10x6", :placeholder => "Update list description..." %>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer"> 
			<small class="pull-left">* Are required fields.</small>
			<a class="form-action btn" data-dismiss="modal">Close</a>
			<a class="form-action"> <%= f.submit "Create", class: "btn btn-success" %> </a>
		</div>
	</div>
<% end %>

<hr>





app/views/lists/new.html.erb
<% provide(:title, 'New List') %>
<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-header" data-original-title>
			<h2><i class="icon-edit"></i><span class="break"></span>New List</h2>
		</div>
		<div class="box-content">
	    		<%= form_for @list, :html => {:multipart => true, :class => "form-horizontal" }  do |f| %>
	    		<fieldset>
					<div class="control-group">
						<label class="control-label" for="focusedInput">List Name</label>
						<div class="controls">
							<div class="input-xlarge focused" id="focusedInput" type="text">
								<%= f.text_field :name, :placeholder => "Give the list a name..." %>
							</div>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="focusedInput">List Description</label>
						<div class="controls">
							<div class="input-xlarge focused" id="focusedInput" type="text">
								<%= f.text_field :description, :placeholder => "Provide a short description..." %>
							</div>
						</div>
					</div>
					<div class="form-actions">
						<%= f.submit "Create", class: "btn btn-large btn-success" %>
					</div>
				</fieldset>
			<% end %>
		</div>
	</div><!--/span-->
</div><!--/row-->

app/views/lists/show.html.erb
<% provide(:title, "List details") %>

<%= will_paginate @problems%>
<body>
  <div class="container-fluid">
    <div class="row-fluid">
        <div class="span12 hero-unit hero-unit-show">
          <h1>#<%=@list.id%> - <%= @list.name %></h1>
          <h2 class="h2-show"><%=@list.description%></h2>
          <p class= "center">
            <% if @list.active %>
              <span class="label label-success label-hero-unit">Active</span>
            <% else %>
              <span class="label label-hero-unit">Closed</span>
            <% end %> 
          </p>  
        </div>
    </div>
  </div>


  <div class="row-fluid fluid-box">
    <div class="span12">
      <div class="box span12">
        <div class="box-header">
          <h2><i class="icon-file"></i><span class="break"></span></h2>
          <div class="box-icon">
            <div class="btn-group">
              <%= link_to list_path(format: "xlsx"), class: 'btn btn-info a-button' do %>
              <i class="icon-download-alt icon-white"></i> Export to .xls
              <% end %>
    <!-- Only have the ability to delete or edit the list if the user is an administrator or the owner of the list -->
              <% if current_user.admin? || current_user.id==@list.user_id %>
                <%= link_to '#', class: 'btn btn-success btn-setting a-button' do %>
                  <i class="icon-edit icon-white"></i> Edit List
                <% end %>

                <%= link_to @list, method: :delete, data: { confirm: "Delete this list?" }, class: 'btn btn-danger a-button' do %>
                  <i class="fa-icon-minus"></i> Delete List
                <% end %>
              <% end %>
            </div>
          </div>




        </div>
        <div class="box-content">
          <table class="table table-striped table-bordered bootstrap-datatable datatable">
            <thead>
              <tr>
                <th>Report</th>
                <th>Picture</th>
                <th>Address</th>
                <th>Description</th>        
                <th>Type</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Date submitted</th>
                <th>Reporter</th>
                <th>Actions</th>
              </tr>
            </thead>   
            <tbody>
              <% @list.problems.each do |problem| %>
                <tr>
                  <td><%= problem.id %></td>
                  <td><%= link_to image_tag(problem.avatar.url(:thumb)), problem %> </td>
                  <td><%= problem.address %></td>
                  <td><%= problem.description %></td>
                  <td><%= problem.get_prob_type %></td>
                  <td><%= problem.get_prob_priority %></td>
                  <td><%= problem.get_prob_status %></td>
                  <td><%= problem.created_at.strftime(" %b.%d %Y") %></td>
                  <td><%= problem.get_owner_name %></td>
                  <td>
      <!-- Only display the option to remove reports from a list if current user is owner or admin
        Make it impossible to remove a resolved report from the list -->
                    <% if problem.status != 3 && (current_user.admin? || current_user.id == @list.user_id)  %>
                      <%= link_to remove_problem_list_path(list: @list,  problem_id: problem.id), class: 'btn btn-mini btn-danger', method: :delete, :confirm => 'Are you sure you wish to remove this report from the list?' do %>
                        <i>Remove</i> 
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

<%= will_paginate @problems%>


<!-- Modal window to edit report details...............................................................-->

<%= form_for @list, :html => {:class => "form-horizontal"} do |f| %>

<div class="modal hide fade" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"></button>
    <h3>Edit List Details</h3>
  </div>

  <div class="modal-body">
    <div class="control-group">
      <label class="control-label" for="focusedInput">List Name</label>
      <div class="controls">
        <div class="input-xlarge focused" id="focusedInput" type="text">
          <%= f.text_field :name %>        
        </div>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="focusedInput">Description</label>
      <div class="controls">
        <div class="input-xlarge focused" id="focusedInput" type="text">
          <%= f.text_area :description, size: "10x6"%>
        </div>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="focusedInput">Active?</label>
      <div class="controls">
        <div class="input-xlarge focused" id="focusedInput" type="text">
          <%= f.check_box(:active) %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer"> 
    <a class="form-action btn" data-dismiss="modal">Close</a>
    <a class="form-action"> <%= f.submit "Update", class: "btn btn-success" %> </a>
  </div>
</div>
<% end %>

app/views/lists/show_problems.html.erb
<% provide(:title, 'Reportes a añadir') %>
<h1>Reportes: <%= @list.name %></h1>

<table>
  <tr>
    <th>Añadir</th>
    <th>Reporte</th>
  </tr>

<% @list.candidate_problems.each do |p| %>
	<tr>
	    <td><%=check_box_tag p.id, 1, @list.in_list?(p), 
		  :onclick => remote_function(
		  :url => save_list_path(@list), 
		  :with => "'problem=#{p.id}&amp;show=' + this.checked", 
		  :method => :post) %>
		</td>	
		<td><%= p.description %></td>
	</tr>
<% end %>
</table>

<%= link_to 'Back', list_path(@list) %>