config/routes.rb
Km7::Application.routes.draw do
devise_for :users

resources :problems
resources :users
resource :user, only: [:show] do
  collection do
    put 'update_password'
  end
end
namespace :api do
  namespace :v1  do
    resources :tokens,:only => [:create, :destroy]
  end
end

resources :lists do
  member do
    put "add_problem_list:problem_id", action: :add_problem, as: :add_problem
    delete "remove_problem_list/:problem_id", action: :remove_problem, as: :remove_problem
  end
end


  match '/new_user',  to: 'users#new'
  match '/users', to: 'users#index'
  match '/edit_user', to: 'users#edit'
  

  match '/reports', to: 'problems#index'
  match '/report', to: 'problems#new'
  get '/problems/map'
  match '/reports/map', to: 'problems#map'


  match '/lists', to: 'lists#index'
  match '/new_list', to: 'lists#new'

  devise_scope :user do
  root to: "devise/sessions#new"
  end

  match '/help',    to: 'static_pages#help'
  match '/about_us',   to: 'static_pages#about'
  match '/contact_us', to: 'static_pages#contact'
  match '/dashboard', to: 'static_pages#admin_dashboard'

  match "/problems/add_new_comment" => "problems#add_new_comment", :as => "add_new_comment_to_problems", :via => [:post]
  match "/problems/:id/delete_comment" => "problems#delete_comment", :as => "delete_comment_from_problems", :via => [:delete]












end

app/models/problem.rb
# == Schema Information
#
# Table name: problems
#
#  id          :integer         not null, primary key
#  user_id     :integer
#  latitude    :float
#  longitude   :float
#  ptype       :integer
#  description :string(255)
#  priority    :integer
#  status      :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#
class Problem < ActiveRecord::Base
#	acts_as_xlsx :columns => [:id, :title, :latitude, :longitude, :ptype, :description, 
#		:priority, :status, :created_at, :updated_at, :address, :municipality, :user_id, 
#		:assigned_at, :resolved_at, :resolved_id]
	belongs_to :user
	has_and_belongs_to_many :lists

	acts_as_commentable

	attr_reader :avatar_remote_url

	#Mapping column information to gmaps marker
	acts_as_gmappable :latitude => 'latitude', :longitude => 'longitude', :process_geocoding => :geocode?,
                  :address => "address", :normalized_address => "address",
                  :msg => "We're sorry, not even google can find that address, please try again."

	attr_accessible :user_id, :title, :latitude, :longitude, :ptype, :description, :avatar, :address, 
	:municipality, :status, :priority, :assigned_at, :resolved_at, :resolved_id

	#The following must be present for the report to be worth anything,
	#Title validation is commented because mobile app still does not provide one and validation would prevent upload.
	#validates(:title, presence: true, uniqueness: true)
	#validates(:title, presence: true)
	validates(:user_id, presence: true)
	validates(:latitude, presence: true)
	validates(:longitude, presence: true)
	validates(:ptype, presence: true)


	#Determine where to store image related to report, in production
	#and in development mode
	if Rails.env.production?
  	has_attached_file :avatar, :styles => {:medium => "767x575#", :thumb => "100x100#"},
					:path => ":rails_root/public/assets/problems/:id/:style/:basename.:extension",
                    :storage => :s3,
					:url => "/assets/problems/:id/:style/:basename.:extension",  
					:s3_credentials => "#{Rails.root}/config/s3.yml",
					:bucket => "km7";
	else
  	has_attached_file :avatar, :styles => {:medium => "767x575", :thumb => "100x100#"},
  					:path => ":rails_root/public/assets/problems/:id/:style/:basename.:extension",
					:url => "/assets/problems/:id/:style/:basename.:extension";
	end

	#Make sure the image attachments are submitted
	validates_attachment_presence :avatar
	validates_attachment_size :avatar, :less_than => 5.megabytes
	validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']

	def gmaps4rails_address
		#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code
		"#{self.latitude}, #{self.longitude}" 
	end

	#def gmaps4rails_infowindow
		#<img src=\"#{self.avatar.url(:thumb)}\"> 
    	#{}"<h1 class='h1-infowindow'>##{self.id} - #{self.title}</h1>
    	#<ul>
        #	<li><strong>Address:</strong> #{self.address}</li>
    	#	<li><strong>Latitude:</strong> #{self.latitude} </li>
    	#	<li><strong>Longitude:</strong> #{self.longitude} </li>
   		#	<li><strong>Status:</strong> #{self.get_prob_status} </li>
   		#	<li><strong>Priority:</strong> #{self.get_prob_priority}</li>
    	#</ul>"
    #end

    def gmaps4rails_title
    	"#{self.description}"
    end

    def geocode?
  		#(!address.blank? && (latitude.blank? || longitude.blank?)) || address_changed?
	end

# Helper methods to map integer properties to string values for UI purposes
	def get_owner_name

		@owner = User.find(self.user_id)
		@owner_name = "No last name"
		if @owner.last_name
			@owner_name = @owner.name + " " + @owner.last_name
		end

		return @owner_name
	end

	def is_in_list?
#Este search se debe hacer para las listas activas porque buscar por todas 
#las listas que existen no hace sentido
		@lists = List.all
		@lists.each do |list|
			if list.problems.include?(self)
				return true
			end
		end
		return false
	end

	def get_containing_list
		@lists = List.all
		@lists.each do |list|
			if list.problems.include?(self)
				return list
			end
		end
	end

	def get_prob_type
	    case self.ptype
	    when 1
	       "Pothole"
	    when 2
	       "Water pipe"
	    when 3
	       "Electric cable"
	    when 4
	       "Light post"
	    when 5
	       "Debris in road"
	    when 6
	       "Vandalism"
	    when 7
	       "Manhole cover"
	    else
	       "Unspecified"
	    end
	 end

	def get_prob_status
		case self.status
		when 1
	       "Pending"
	    when 2
	       "Assigned"
	    when 3
	       "Resolved"
	    else
	       "Unspecified"
	    end
	end

	def get_prob_priority
		case self.priority
		when 1
	       "Low"
	    when 2
	       "Normal"
	    when 3
	       "High "
	    else
	       "Unspecified"
	    end
	end

end


app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

  def new
    @problem = Problem.new
    @lists = List.all
  end

#Show report details and only show selected problem in gmap
  def show
    @problem = Problem.find(params[:id])
    @json = @problem.to_gmaps4rails do |problem, marker|
      marker.infowindow render_to_string(:partial => "/problems/report_infowindow", :locals => { :problem => problem})
      marker.picture({
                :picture => "/assets/markers/#{problem.ptype}.png",
                :width   => 32,
                :height  => 35
                 })
      marker.title   "##{problem.id}#{problem.get_prob_type}"
      marker.json({ :id => problem.id})
    end
  end

#Show list of reports and show all of them in gmap 
  def index
    @problems = Problem.paginate(page: params[:page])
  end

  def create

    #Line added to debug POST requests from mobile app
    puts params[:problem]

    @problem = Problem.new(params[:problem])
    
#This works only for dev purposes for submitting reports from the web application 
#and set the curret_user as the reporting, if the submitting problem has no id
#assign the current_user as owner.
    if !@problem.user_id
      @problem.user_id = current_user.id
    end
#Geocoding addresses to coordinates does not work well in Puerto Rico hence its implementationwill be postponed or abandoned
   #@geocoded = Gmaps4rails.geocode(@problem.address)
   #puts @geocoded

#When report is first created, its status is initially Unassigned, hence it is set to 1
    @problem.status = 1

    if @problem.save
      flash[:success] = "Report saved"
      #render :status =>200
      #@lists.problems.create(attributes={"list_id" =>3, "problem_id" => @problem.id})
      redirect_to @problem
    else
      flash[:error] = 'Incomplete information, report not created'
      redirect_to problems_url
    end
  end

  def destroy
    Problem.find(params[:id]).destroy
    flash[:success] = "Report deleted."
    redirect_to problems_url
  end

  #Before_filter for these methods edit/update to confirm the user is the owner of these reports
  #as in user.rb, rails tutorial
  def edit
    @problem = Problem.find(params[:id])
  end

  def update
    @problem = Problem.find(params[:id])
    if @problem.update_attributes(params[:problem])
      flash[:success] = "Report updated"
      redirect_to @problem
    else
      flash[:error] = "Report update error"
      redirect_to @problem
    end
  end

  def add_new_comment
    @problem = Problem.find(params[:id])
    @comment = Comment.build_from( @problem, current_user.id, params[:comment][:body] )
    @comment.save!
    flash[:notice] = "Comment added!"
    redirect_to :action => :show, :id => @problem
  end

  def delete_comment
      @problem = Problem.find(params[:id])
      @comment = Comment.find(params[:comment])

      if current_user.id == @comment.user_id
          @comment.destroy
          flash[:notice] = "Comment deleted!"
      else
          flash[:notice] = "Sorry, you can't delete this comment"
      end
      redirect_to :action => :show, :id => @problem
  end

  def map
      @json = Problem.all.to_gmaps4rails do |problem, marker|
      marker.infowindow render_to_string(:partial => "/problems/map_infowindow", :locals => { :object => problem})
      marker.picture({
                :picture => "/assets/markers/#{problem.ptype}.png",
                :width   => 32,
                :height  => 35
                 })
      marker.title   "##{problem.id} - #{problem.get_prob_type}"
      marker.json({ :id => problem.id})
    end
  end

=begin  
  def get_last_month_reports
    @last_month = 0
    Problem.all.each do |problem|
      if problem.created_at.month == Time.1.month.ago
        @last_month = @last_month +1
      end
    end
    return @last_month
  end



def get_before_last_month_reports
    @before_last_month = 0
    Problem.all.each do |problem|
      if problem.created_at.month == 2.month.ago
        @last_month = @last_month +1
      end
    end
    return @last_month
  end
=end

#    def get_type_count
#    @report_type_count = Problem.where("ptype = 1").count
#
#    return @report_type_count
#    end

#Parameters: {"utf8"=>"√", "authenticity_token"=>"yuxdf1QkhDuuRnAV+qVSTjt0aq3Yo1sW9UN685GhEMc=", 
#  "problem"=>{"user"=>"7876483097", "latitude"=>"18.378383", "longitude"=>"-67.026201", "ptype"=>"2", 
#    "description"=>"Poste roto"}, "commit"=>"Guardar problema"}
# title=This+is+a+test+post+title&latitude=18.09&longitude=-67.12&ptype=2&status=1&priority=2&description=This+is+a+test+description+from+and+http+post&user_id=1
end

app/helpers/problems_helper.rb
module ProblemsHelper

end

app/views/problems/_map_infowindow.html.erb
    <h1 class='h1-infowindow'>#<%= object.id %> - <%= object.get_prob_type %></h1>
   	<ul>
   		<li><strong>Status:</strong> <%= object.get_prob_status %> </li>
   		<li><strong>Priority:</strong> <%= object.get_prob_priority %></li>
   		<li><strong>Description:</strong> <%= object.description %></li>
   		<li><strong><%= link_to "...more", object, :target => "_blank"%></strong> </li>
	</ul>

app/views/problems/_prob_fields.html.erb
<fieldset>
	<p>*Please fill out every field</p>
	<div class="control-group">
		<label class="control-label" for="focusedInput">Report Title</label>
			<div class="controls">
				<div class="input-xlarge focused" id="focusedInput" type="text">
					<%= f.text_field :title, :placeholder => "Give the report a title..." %>
				</div>
			</div>
	</div>


	<div class="control-group">
		<label class="control-label" for="focusedInput">Description</label>
			<div class="controls">
				<div class="input-xlarge focused" id="focusedInput" type="text">
					<%= f.text_field :description, :placeholder => "Update situation and location description..." %>
				</div>
			</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="focusedInput">Type</label>
			<div class="controls">
				<div class="input-xlarge focused" id="focusedInput" type="text">
					<%= f.select :ptype, [["Pothole", 1], ["Water pipe", 2], ["Electric cable", 3], 
	               	["Light post", 4], ["Debris on road", 5], ["Vandalism", 6], ["Manhole cover", 7], 
	               	["Other", 8]] %>				
               	</div>
			</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="focusedInput">Status</label>
			<div class="controls">
				<div class="input-xlarge focused" id="focusedInput" type="text">
					<%= f.select :priority, [["Unassigned", 1], ["Assigned", 2], ["Resolved", 3]] %>
				</div>
			</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="focusedInput">Priority</label>
			<div class="controls">
				<div class="input-xlarge focused" id="focusedInput" type="text">
					<%= f.select :status, [["Low", 1], ["Medium", 2], ["High", 3]] %>
				</div>
			</div>
	</div>

	<div class="form-actions">
		<%= f.submit "Update", class: "btn btn-large btn-success" %>
	</div>

</fieldset>


app/views/problems/_problem.html.erb
<li>
  
  <img src="<%=problem.avatar.url(:thumb) %>">
  Reporte #<%= problem.id %>
  <%= link_to "Show", problem %>
    	| <%= link_to "Edit", edit_problem_path(problem) %>
  <% if current_user.admin? %>
  	| <%= link_to "Delete", problem, method: :delete, data: { confirm: "Are you sure you want to delete this report?" } %>
  <% end %>

</li>

app/views/problems/_report_infowindow.html.erb
    <h1 class='h1-infowindow'>#<%= @problem.id %> - <%= @problem.get_prob_type %></h1>
   	<ul>
       	<li><strong>Address:</strong> <%= @problem.address %></li>
   		<li><strong>Latitude:</strong> <%= @problem.latitude %> </li>
   		<li><strong>Longitude:</strong> <%= @problem.longitude %></li>
	</ul>

app/views/problems/create.html.erb
<h1>Problems#create</h1>
<p>Find me in app/views/problems/create.html.erb</p>

app/views/problems/destroy.html.erb
<h1>Problems#destroy</h1>
<p>Find me in app/views/problems/destroy.html.erb</p>

app/views/problems/index.html.erb
<% provide(:title, 'Reports') %>

<%= will_paginate %>


<div class="row-fluid fluid-box">
	<div class="box span12">
		<div class="box-header">
			<h2><i class="icon-file"></i><span class="break"></span></h2>

			<div class="box-icon">
				<%= link_to "#", class: 'btn btn-success btn-setting' do %>
				<i class="icon-plus"></i> New Report
				<% end %>
			</div>

		</div>
		<div class="box-content">
			<ul class="nav tab-menu nav-tabs tabs-lists" id="myTab">
				<li class="active"><a href="#active">Active Reports</a></li>
				<li><a href="#resolved">Resolved Reports</a></li>
			</ul>

			<div id="myTabContent" class="tab-content">
				<div class="tab-pane active" id="active">
					<table class="table table-striped table-bordered bootstrap-datatable datatable">
						<thead>
							<tr>
								<th>Report</th>
								<th>Picture</th>
								<th>Address</th>
								<!--th>Title</th-->			  
								<th>Type</th>
								<th>Priority</th>
								<th>Status</th>
								<th>Date submitted</th>
								<th>Reporter</th>
								<th>Actions</th>
							</tr>
						</thead>   
						<tbody>
<!-- Show only reports whose status is NOT 3 (Resolved)-->
							<% @problems.where("status NOT IN(?)", 3).each do |problem| %>

							<tr>
								<td><%= problem.id %></td>
								<td><%= link_to image_tag(problem.avatar.url(:thumb)), problem %> </td>
								<td><%= problem.address %></td>
								<!--td><%= problem.title %></td-->
								<td><%= problem.get_prob_type %></td>
								<td><%= problem.get_prob_priority %></td>
								<td><%= problem.get_prob_status %></td>
								<td class="center"><%= problem.created_at.strftime(" %b.%d %Y") %></td>
								<td><%=problem.get_owner_name%> </td>

								<!--Action buttons for problem index table, Delete and More Info -->
								<td class="center">
									<%= link_to problem, class: 'btn btn-info' do %>
									<i class="icon-zoom-in icon-white"></i> 
									<% end %>

									<% if current_user.admin? && problem.status != 3%>
									<%= link_to problem, method: :delete, data: { confirm: "Delete this report?" }, class: 'btn btn-danger' do %>
									<i class="icon-trash icon-white"></i> 
									<% end %>
									<% end %>

								</td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>

				<div class="tab-pane" id="resolved">
					<table class="table table-striped table-bordered bootstrap-datatable datatable">
						<thead>
							<tr>
								<th>Report</th>
								<th>Picture</th>
								<th>Address</th>
								<!--th>Title</th-->			  
								<th>Type</th>
								<th>Priority</th>
								<th>Status</th>
								<th>Date submitted</th>
								<th>Reporter</th>
								<th>Actions</th>
							</tr>
						</thead>   
						<tbody>
<!-- Show only resolved reports -->
							<% @problems.where(status: 3).each do |problem| %>
							<tr>
								<td><%= problem.id %></td>
								<td><%= link_to image_tag(problem.avatar.url(:thumb)), problem %> </td>
								<td><%= problem.address %></td>
								<!--td><%= problem.title %></td-->
								<td><%= problem.get_prob_type %></td>
								<td><%= problem.get_prob_priority %></td>
								<td><%= problem.get_prob_status %></td>
								<td class="center"><%= problem.created_at.strftime(" %b.%d %Y") %></td>
								<td><%=problem.get_owner_name%> </td>
								<!--Action buttons for problem index table, Delete and More Info -->
								<td class="center">
									<%= link_to problem, class: 'btn btn-info' do %>
									<i class="icon-zoom-in icon-white"></i> 
									<% end %>

									<% if current_user.admin? && problem.status != 3%>
									<%= link_to problem, method: :delete, data: { confirm: "Delete this report?" }, class: 'btn btn-danger' do %>
									<i class="icon-trash icon-white"></i> 
									<% end %>
									<% end %>

								</td>
							</tr>
							<% end %>
						</tbody>
						</table>
					</div>

				</div>
			</div>
		</div>
	</div>
	<%= will_paginate %>

	<%= form_for :problem, :html => {:class => "form-horizontal"} do |f| %>

	<div class="modal hide fade" id="myModal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"></button>
			<h3>New Report</h3>
		</div>

		<div class="modal-body">
			<div class="control-group">
				<label class="control-label" for="focusedInput">*Title</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_field :title,  :maxlength=>'30', :placeholder => "Please provide a title..." %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="focusedInput">Address</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_area :address, size: "10x2" %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="focusedInput">Municipality</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_field :municipality %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="focusedInput">*Latitude</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_field :latitude %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="focusedInput">*Longitude</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_field :longitude %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="focusedInput">*Type</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.select :ptype, [["Pothole", 1], ["Water pipe", 2], ["Electric cable", 3], 
						["Light post", 4], ["Debris on road", 5], ["Vandalism", 6], ["Manhole cover", 7], 
						["Other", 8]] %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="focusedInput">Priority</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.select :priority, [["Low", 1], ["Medium", 2], ["High", 3]] %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="focusedInput">*Image</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.file_field :avatar %>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="textarea2">Description</label>
				<div class="controls">
					<div class="input-xlarge focused" id="focusedInput" type="text">
						<%= f.text_area :description, :placeholder => "Provide a short description of the situation and/or location...", size: "10x6" %>
					</div>
				</div>
			</div>
			<div class="modal-footer"> 
				<small class="pull-left">* Are required fields.</small>
				<a class="form-action btn" data-dismiss="modal">Close</a>
				<a class="form-action"> <%= f.submit "Create", class: "btn btn-success" %> </a>
			</div>
		</div>
	</div>
	<% end %>

app/views/problems/map.html.erb
<% provide(:title, 'Dashboard') %>


<html lang="en">
<body>	
	<!--div id="content" class="span10"-->
	<!-- start: Content -->

	<div class="row-fluid fluid-box">
		<div class="box span12">
			<div class="box-header" data-original-title>
				<h2><i class="fa-icon-globe"></i><span class="break"></span>Reports Global</h2>
			</div>
			<div class="box-content">
				<div class="row-fluid">
            		<div class="span12">
              			<%= gmaps({"map_options" => {"auto_zoom" => false, "zoom" => 10, :container_class => "map_view_container" },"markers" => {"data" => @json }})%>
            		</div>
				</div>
			</div>
		</div>  
	</div>
<!-- end: Content -->
<!--/div-->
<!--/#content.span10-->
</body>
</html>

app/views/problems/new.html.erb
<% provide(:title, 'New Report') %>
<div class="row-fluid fluid-box">
  <div class="box span12">
    <div class="box-header" data-original-title>
      <h2><i class="icon-edit"></i><span class="break"></span>New Report</h2>
    </div>
    <div class="box-content">
          <%= form_for @problem, :html => {:multipart => true, :class => "form-horizontal" }  do |f| %>
          <fieldset>
          <div class="control-group">
            <label class="control-label" for="focusedInput">Title</label>
            <div class="controls">
              <div class="input-xlarge focused" id="focusedInput" type="text">
                <%= f.text_field :title, :placeholder => "Please provide a title..." %>
              </div>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="focusedInput">Latitude</label>
            <div class="controls">
              <div class="input-xlarge focused" id="focusedInput" type="text">
                <%= f.text_field :latitude %>
              </div>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="focusedInput">Longitude</label>
            <div class="controls">
              <div class="input-xlarge focused" id="focusedInput" type="text">
                <%= f.text_field :longitude %>
              </div>
            </div>
          </div>

         <div class="control-group">
           <label class="control-label" for="focusedInput">Type</label>
           <div class="controls">
             <div class="input-xlarge focused" id="focusedInput" type="text">
             <%= f.select :ptype, [["Pothole", 1], ["Water pipe", 2], ["Electric cable", 3], 
               ["Light post", 4], ["Debris on road", 5], ["Vandalism", 6], ["Manhole cover", 7], 
               ["Other", 8]] %>
             </div>
           </div>
         </div>

        <div class="control-group">
            <label class="control-label" for="focusedInput">Status</label>
              <div class="controls">
                <div class="input-xlarge focused" id="focusedInput" type="text">
                  <%= f.select :status, [["Unassigned", 1], ["Assigned", 2], ["Resolved", 3]] %>
                </div>
              </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="focusedInput">Priority</label>
              <div class="controls">
                <div class="input-xlarge focused" id="focusedInput" type="text">
                  <%= f.select :priority, [["Low", 1], ["Medium", 2], ["High", 3]] %>
                </div>
              </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="focusedInput">Image</label>
            <div class="controls">
              <div class="input-xlarge focused" id="focusedInput" type="text">
                <%= f.file_field :avatar %>
              </div>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="textarea2">Description</label>
            <div class="controls">
              <div class="input-xlarge focused" id="focusedInput" type="text">
                <%= f.text_area :description, :placeholder => "Provide a short description of the situation and/or location...", size: "10x6" %>
              </div>
            </div>
          </div>


          <div class="form-actions">
            <%= f.submit "Create", class: "btn btn-success" %>
            <%= link_to reports_path, data: { confirm: "Abandon report submission?" }, class: 'btn' do %>
              <i></i> Cancel
            <% end %>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div><!--/span-->
</div><!--/row-->