config/routes.rb
Km7::Application.routes.draw do
devise_for :users

resources :problems
resources :users
resource :user, only: [:show] do
  collection do
    put 'update_password'
  end
end
namespace :api do
  namespace :v1  do
    resources :tokens,:only => [:create, :destroy]
  end
end

resources :lists do
  member do
    put "add_problem_list:problem_id", action: :add_problem, as: :add_problem
    delete "remove_problem_list/:problem_id", action: :remove_problem, as: :remove_problem
  end
end


  match '/new_user',  to: 'users#new'
  match '/users', to: 'users#index'
  match '/edit_user', to: 'users#edit'
  

  match '/reports', to: 'problems#index'
  match '/report', to: 'problems#new'
  get '/problems/map'
  match '/reports/map', to: 'problems#map'


  match '/lists', to: 'lists#index'
  match '/new_list', to: 'lists#new'

  devise_scope :user do
  root to: "devise/sessions#new"
  end

  match '/help',    to: 'static_pages#help'
  match '/about_us',   to: 'static_pages#about'
  match '/contact_us', to: 'static_pages#contact'
  match '/dashboard', to: 'static_pages#admin_dashboard'

  match "/problems/add_new_comment" => "problems#add_new_comment", :as => "add_new_comment_to_problems", :via => [:post]
  match "/problems/:id/delete_comment" => "problems#delete_comment", :as => "delete_comment_from_problems", :via => [:delete]












end

app/views/layouts/_flash_messages.html.erb
  <% flash.each do |key, value| %>
  	<% if value != "" %>
	    <div class="<%= flash_class(key) %> fade in">
	      <a href="#" data-dismiss="alert" class="close">×</a>
	      <%= value %>
	    </div>
    <% end %>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      <p>
        <span style="text-align:left;float:left">&copy; <a href="http://www.kilometrosiete.com/" target="_blank">Kilómetro Siete</a> 2013</span>
        <!--span style="text-align:right;float:right">By: <a href="#">nanomachine</a></span-->
      </p>
  </small>
  <%= yield :scripts %>
  <nav>
    <ul>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "About Us",   about_us_path %></li>
      <li><%= link_to "Contact Us",   contact_us_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "Kilómetro Siete", '/', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>


              <li id= "fat-menu">
                <%=link_to "Welcome back, " + current_user.name , current_user %>
              </li>

              <li id= "fat-menu">
                  <%= link_to "Sign Out", destroy_user_session_path, method: "delete" %>
              </li>
          <% else %>
            <!--li id= "fat-menu">
              < %= link_to "Sign up", new_user_path %> 
            </li-->
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_landing_footer.html.erb
<footer class="landing_footer">
  <small>
      <p>
        <span style="text-align:left;float:left">&copy; <a href="http://www.kilometrosiete.com/" target="_blank">Kilómetro Siete</a> 2013</span>
        <!--span style="text-align:right;float:right">By: <a href="#">nanomachine</a></span-->
      </p>
  </small>
  <%= yield :scripts %>
  <nav>
    <ul>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "About Us",   about_us_path %></li>
      <li><%= link_to "Contact Us",   contact_us_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb

<% if user_signed_in? %>

<div id="menu-bar-content">	
	<div class="row-fluid menu-bar-fixed fluid-box">
		<a href="/dashboard" class="quick-button span2">
			<i class="fa-icon-dashboard"></i>
			<p>Dashboard</p>
		</a>
				
		<a href="/users" class="quick-button span2">
			<i class="fa-icon-group"></i>
			<p>Users</p>
			<span class="notification"><%= User.count %></span>
		</a>
	
		<a href="/reports" class="quick-button span2">
			<i class="fa-icon-eye-open"></i>
			<p>Reports</p>
			<span class="notification green"><%= Problem.count %></span>
		</a>

		<a href="/lists" class="quick-button span2">
			<i class="fa-icon-th-list"></i>
			<p>Lists</p>
			<span class="notification red"><%= List.count %></span>
		</a>
		
		<a href="/reports/map" class="quick-button span2">
			<i class="fa-icon-globe"></i>
			<p>Map</p>
		</a>

		<a href="/users/<%= current_user.id %>"class="quick-button span2">
			<i class="fa-icon-user"></i>
			<p>My Profile</p>
		</a>

		<!--a class="quick-button span2">
			<i class="fa-icon-cog"></i>
			<p>Settings</p>
		</a-->

		<hr>

	</div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_link_tag "gmaps4rails" %>
    <%= csrf_meta_tag %>
    <%= include_gon %>
    <%= javascript_include_tag "application" %>

    <!--[if lt IE 7 ]>
    <link id="ie-style" href="style-ie.css.scss" rel="stylesheet">
    <![endif]-->
    <!--[if IE 8 ]>
  <link id="ie-style" href="style-ie.css.scss" rel="stylesheet">
    <![endif]-->
    <!--[if IE 9 ]>
    <![endif]-->

    <%= render 'layouts/shim' %>      
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= render 'layouts/sidebar' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <!-- % debug(params) if Rails.env.development? % -->
    <% if current_user %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>